### PR TITLE
Added doc on how to run on OKD 4.0.0

### PR DESCRIPTION
**Pull request by gustavonalle**

### CODE REVIEW

**Comment by gustavonalle** [comment]
Fixed conflicts

**Comment by rigazilla** [comment]
I'm trying this with [oc-cluster-up](https://github.com/gustavonalle/oc-cluster-up). 

```
alias okd='docker exec -it openshift-master oc'
$ okd policy add-role-to-user view system:serviceaccount:$(okd project -q):default -n $(okd project -q)
Error from server (NotFound): namespaces "default\r" not found
```
``okd project -q`` returns a toxic "\r" on my system

however hardcoding the project name the command works

**Comment by gustavonalle** [comment]
Can you test with only `oc` without the alias?
Btw, there is another [PR](https://github.com/rigazilla/infinispan-operator/pull/6) that makes the ```add-role-to-user``` unecessary.

**Comment by rigazilla** [comment]
tried with a "real" oc. OK merging

**Comment by rigazilla** [comment]
thanks

**Pull request merged**
